site_name: PSDsHook
repo_url: https://github.com/gngrninja/PSDsHook
theme: readthedocs
nav:
  - Home: index.md
  - Reference: 
    - Functions: 
      - Invoke-PSDsHook: reference/functions/Invoke-PSDsHook.md
  - Examples:
      - Configuration Creation: tutorials/CreateConfig.md
      - Embeds: tutorials/Embeds.md
      - Embeds With Fields: tutorials/EmbedsWithFields.md
      - Sending a simple message: tutorials/SimpleMessage.md
